CREATE TABLE [dbo].[Flights] (
    [Flight_refnum]          INT      IDENTITY (1, 1) NOT NULL,
    [Glider_Pilot_Name]      INT      NULL,
    [Instructor_name]        INT      NULL,
    [Passenger_name]         INT      NULL,
    [OD1]                    INT      NULL,
    [OD2]                    INT      NULL,
    [OD3]                    INT      NULL,
    [AOD1]                   INT      NULL,
    [AOD2]                   INT      NULL,
    [TowPilot1]              INT      NULL,
    [TowPilot2]              INT      NULL,
    [TowPilot3]              INT      NULL,
    [TowPlane1]              INT      NULL,
    [TowPlane2]              INT      NULL,
    [Date]                   DATE     NULL,
    [Glider_takeoff_time]    TIME (0) NULL,
    [Glider_landing_time]    TIME (0) NULL,
    [Tow_takeoff_time]       TIME (0) NULL,
    [Tow_landing_time]       TIME (0) NULL,
    [Altitude_towed]         INT      NULL,
    [Rope_break]             INT      NULL,
    [Airport_name]           INT      NULL,
    [Flight_minutes]         TIME (0) NULL,
    [First_name_on_invoice]  INT      NULL,
    [Split_cost]             BIT      DEFAULT ((0)) NULL,
    [Percent_1st_check]      INT      DEFAULT ((100)) NULL,
    [Second_name_on_invoice] INT      NULL,
    [Penalty_charge]         BIT      DEFAULT ((0)) NULL,
    [Cost_this_flight]       MONEY    NULL,
    PRIMARY KEY CLUSTERED ([Flight_refnum] ASC),
    CONSTRAINT [FK_Flights_TowPlane2] FOREIGN KEY ([TowPlane2]) REFERENCES [dbo].[Aircraft] ([Aircraft_refnum]),
    CONSTRAINT [FK_Flights_TowPlane1] FOREIGN KEY ([TowPlane1]) REFERENCES [dbo].[Aircraft] ([Aircraft_refnum]),
    CONSTRAINT [FK_Flights_Airport] FOREIGN KEY ([Airport_name]) REFERENCES [dbo].[Airport] ([Airport_refnum]),
    CONSTRAINT [FK_Flights_First_name_inv] FOREIGN KEY ([First_name_on_invoice]) REFERENCES [dbo].[Members] ([Member_refnum]),
    CONSTRAINT [FK_Flights_Instructor] FOREIGN KEY ([Instructor_name]) REFERENCES [dbo].[Members] ([Member_refnum]),
    CONSTRAINT [FK_Flights_Second_name_inv] FOREIGN KEY ([Second_name_on_invoice]) REFERENCES [dbo].[Members] ([Member_refnum]),
    CONSTRAINT [FK_Flights_OD1] FOREIGN KEY ([OD1]) REFERENCES [dbo].[Members] ([Member_refnum]),
    CONSTRAINT [FK_Flights_OD2] FOREIGN KEY ([OD2]) REFERENCES [dbo].[Members] ([Member_refnum]),
    CONSTRAINT [FK_Flights_AOD1] FOREIGN KEY ([AOD1]) REFERENCES [dbo].[Members] ([Member_refnum]),
    CONSTRAINT [FK_Flights_AOD2] FOREIGN KEY ([AOD2]) REFERENCES [dbo].[Members] ([Member_refnum]),
    CONSTRAINT [FK_Flights_TowPilot2] FOREIGN KEY ([TowPilot2]) REFERENCES [dbo].[Members] ([Member_refnum]),
    CONSTRAINT [FK_Flights_TowPilot3] FOREIGN KEY ([TowPilot3]) REFERENCES [dbo].[Members] ([Member_refnum]),
    CONSTRAINT [FK_Flights_Name] FOREIGN KEY ([Glider_Pilot_Name]) REFERENCES [dbo].[Members] ([Member_refnum]),
    CONSTRAINT [FK_Flights_OD3] FOREIGN KEY ([OD3]) REFERENCES [dbo].[Members] ([Member_refnum]),
    CONSTRAINT [FK_Flights_TowPilot1] FOREIGN KEY ([TowPilot1]) REFERENCES [dbo].[Members] ([Member_refnum])
);

